output "instance_public_ip" {
  value       = aws_instance.web.public_ip
  description = "Public IP address of the web server"
}

output "instance_public_dns" {
  value       = aws_instance.web.public_dns
  description = "Public DNS of the web server"
}

output "ssh_user" {
  value       = "ubuntu"
  description = "Default SSH user for Ubuntu AMI"
}

output "ansible_inventory_hint" {
  value       = "ansible/inventory.ini will be generated by scripts/deploy.sh"
  description = "Hint for automation script"
}
